#include "UserConfig.h"
#include <WiFi.h>

/*
    Global variables
*/
// The Wifi credentials
const char* WIFI_NAME = "BKR-HotSpot";
const char* WIFI_PASSWORD = "";

// Ip-Credentials
const bool IP_USE_DHCP = false;
const IPAddress IP_STATIC_IP(10,200,9,55);
const IPAddress IP_STATIC_GATEWAY(10,200,15,254);
const IPAddress IP_STATIC_SUBNETMASK(255,255,248,0);
const IPAddress IP_STATIC_DNS(10,200,15,254);

// The address of the server to send the data to 
const char* MASTER_SERVER = "10.200.9.23:5000";

// Id of this device
const int DEVICE_ID = 400;

// All known devices that the building-client should request data from
const int KNOWN_DEVICES[] = {1,2,3,4,5,6};

/*
    Autogenerated
*/
// All known devices that the building-client should request data from
const int KNOWN_DEVICES_AMOUNT = sizeof(KNOWN_DEVICES)/sizeof(int);
